src/objects/Chat_Conversation__c.object
<CustomObject>
    <description>Conversations over chat messaging.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact involved in the conversation.</description>
        <inlineHelpText>Contact involved in the conversation.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Chat Conversations</relationshipLabel>
        <relationshipName>Chat_Conversations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conversation__c</fullName>
        <description>Actual conversation between user and contact/anonymous visitor.</description>
        <inlineHelpText>Actual conversation between user and contact/anonymous visitor.</inlineHelpText>
        <label>Conversation</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead involved in a chat conversation.</description>
        <inlineHelpText>Lead involved in a chat conversation.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Chat Conversations</relationshipLabel>
        <relationshipName>Chat_Conversations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message posted by individual involved in conversation.</description>
        <inlineHelpText>Message posted by individual involved in conversation.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of conversation.</description>
        <inlineHelpText>Shows the status of conversation.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ended by Agent</fullName>
                </value>
                <value>
                    <fullName>Inititated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Ended by Visitor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Name__c</fullName>
        <formula>Contact__r.FirstName + &apos; &apos; + Contact__r.LastName +  Lead__r.FirstName + &apos; &apos; + Lead__r.LastName</formula>
        <label>Visitor Name</label>
        <type>Text</type>
    </fields>
    <label>Chat Conversation</label>
    <nameField>
        <displayFormat>Conv-{000000}</displayFormat>
        <label>Chat Conversation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgentChatClientController.cls
public class AgentChatClientController{
    
    public Chat_Conversation__c chatConv { get; set; }
    public String message { get; set; }
    
    public AgentChatClientController(){
        Id id = apexpages.currentpage().getparameters().get('id');
        if(id != null){
            List<Chat_Conversation__c> chatConvList = [Select Id, Contact__c, Conversation__c, Lead__c, Message__c, Status__c, Visitor_Name__c
                                                       from Chat_Conversation__c where Id =: id];
            if(!chatConvList.isEmpty()){
                chatConv = chatConvList.get(0);
                message = chatConv.Message__c;
                if(message != null && message != '' && message.contains('Visitor:#'))
                    message = message.replace('Visitor:#', chatConv.Visitor_Name__c + ': ');
            }    
        }

    }
    
    public void sendMessage(){
        
        if(chatConv != null && chatConv.Status__c != 'In Progress')
            chatConv.Status__c = 'In Progress';
        if(chatConv.Message__c != null && chatConv.Message__c != '')
            update chatConv;
    }
    
    

}